import type { ImportedFile, ParsedItem } from "./types";

const defaultItems: ParsedItem[] = [
  {
    title: "First midterm",
    date: "2026-09-18",
    type: "Exam",
    notes: "Autogenerated sample item until live parsing is connected.",
  },
  {
    title: "Essay draft due",
    date: "2026-09-23",
    type: "Homework",
    notes: "Autogenerated sample item until live parsing is connected.",
  },
  {
    title: "Withdrawal deadline",
    date: "2026-10-02",
    type: "Important date",
    notes: "Autogenerated sample item until live parsing is connected.",
  },
];

export function buildDemoParseResults(file: ImportedFile): ParsedItem[] {
  const baseName = file.name.replace(/\.[^.]+$/, "");

  return defaultItems.map((item, index) => ({
    ...item,
    title: index === 0 ? `${baseName} review` : item.title,
  }));
}
